
subID = 'ONLINESUB';
base_dir = strcat('C:\Users\benri\Documents\GitHub\MILD-Master\Online Behavior\stim\mild-master-online\s_',subID);
fp = fopen('trial_info_play.txt', 'w');
target_words = {'ba','bash'};

all_folders = dir(base_dir);
all_folders(1:2,:) = [];

all_conditions = {'side=l_itd=0_az=10_mag=0_word_set=0',...
    'side=l_itd=0_az=10_mag=0_word_set=1',...
    'side=l_itd=0_az=15_mag=0_word_set=0',...
    'side=l_itd=0_az=15_mag=0_word_set=1',...
    'side=l_itd=0_az=20_mag=0_word_set=0',...
    'side=l_itd=0_az=20_mag=0_word_set=1',...
    'side=l_itd=0_az=5_mag=0_word_set=0',...
    'side=l_itd=0_az=5_mag=0_word_set=1',...
    'side=l_itd=500_az=0_mag=0_word_set=0',...
    'side=l_itd=500_az=0_mag=0_word_set=1',...
    'side=l_itd=50_az=0_mag=0_word_set=0',...
    'side=l_itd=50_az=0_mag=0_word_set=1',...
    'side=r_itd=0_az=10_mag=0_word_set=0',...
    'side=r_itd=0_az=10_mag=0_word_set=1',...
    'side=r_itd=0_az=15_mag=0_word_set=0',...
    'side=r_itd=0_az=15_mag=0_word_set=1',...
    'side=r_itd=0_az=20_mag=0_word_set=0',...
    'side=r_itd=0_az=20_mag=0_word_set=1',...
    'side=r_itd=0_az=5_mag=0_word_set=0',...
    'side=r_itd=0_az=5_mag=0_word_set=1',...
    'side=r_itd=500_az=0_mag=0_word_set=0',...
    'side=r_itd=500_az=0_mag=0_word_set=1',...
    'side=r_itd=50_az=0_mag=0_word_set=0',...
    'side=r_itd=50_az=0_mag=0_word_set=1'};

num_conditions = length(all_conditions); % spatialization x attend L/R x word set
ntrialspercondition = 6;

for itrialpercondition = 1:ntrialspercondition
    for icondition = 1:num_conditions % loop through audio files for the online subject
        % use the foldername to find this trial word_type and condition
        this_condition = all_folders(icondition).name;
        this_word_set = str2num(this_condition(end));

        trialfiles = dir(strcat(base_dir,'\',this_condition));
        trialfiles(1:2,:) = [];

        this_trial_info = trialfiles(itrialpercondition).name;
        fprintf(fp, '{\n\"plugin\": \"ben-multi-button-response\",\n');
        fprintf(fp, '\"prompt\": \"Click when you hear the word <strong>%s</strong> from the cued direction\",\n',string(target_words(this_word_set + 1)));
        fprintf(fp, '\"choices\": ["%s"],\n', string(target_words(this_word_set + 1)));
        fprintf(fp, '\"answer\": %s,\n', '1');
        fname = strcat('bashdashgashonline_cond_', num2str(icondition), '_trial_',num2str(itrialpercondition),'.wav');
        fprintf(fp, '\"stimulus\": \"%s\",\n', fname);
        fprintf(fp, '\"cond\": %d,\n', find(all_conditions == string(this_condition)));
        fprintf(fp, '\"annot\": {\"spatial_cue": \"%s\"}\n},\n', this_trial_info);
        itrial = itrial + 1;

        % write the current audiofile name as its pretty name
        [this_audio,this_fs] = audioread(strcat(trialfiles(itrialpercondition).folder,'\',this_trial_info));
        audiowrite(strcat('C:\Users\benri\Documents\GitHub\MILD-Master\Online Behavior\stim\mild-master-online\final online wav files\',fname),this_audio,this_fs);

    end

end
fclose(fp);
